#! /bin/bash
# abrtool version 0.1.5
# Created by boulderjams (http://twitter.com/creativeboulder)
# Android Backup Data and Restore Data Script

#CHANGELOG
# 0.1.5 - Check udev rules (then sudo)
# 0.1.5 - Merged into Android-Linux-Tools
# 0.1.5 - Changed zenity commands (shows restore progress)
# 0.1.5 - Option to restart device after restore
# 0.1.5 - Can install abrtool via command-line (./abrtool --install)

#TODO
# Next update. Check if backup exists. Ask to remove.

#VARIABLES
VERSION=0.1.5
LASTUPDATED=11-21-2009
BACKUPDIR=~/.android-backup
USER=${username-`whoami`}
APP2SD=1

backupscript() {
        export PATH=$PATH:$BACKUPDIR
	sudo echo "Gaining root privleges for adb..."
	sudo adb kill-server
	cd $BACKUPDIR
	if [ -f $BACKUPDIR ]
		then 
			rm -Rvf $BACKUPDIR
	fi
	sudo adb pull /system/sd/app $BACKUPDIR/apps
	sudo adb pull /system/app $BACKUPDIR/apps/device
	echo "---------- Backed Applications"
	sudo adb pull /data/data/com.android.providers.telephony/databases/mmssms.db $BACKUPDIR/msgs/mmssms.db
	echo "---------- Backed Text Messages"
	sudo adb pull /data/data/com.android.browser/databases/browser.db $BACKUPDIR/bookmarks/browser.db
	echo "---------- Backed Bookmarks"
	sudo adb pull /data/data/com.android.alarmclock/databases/alarms.db $BACKUPDIR/other/alarms.db
	sudo adb pull /data/data/com.google.android.providers.settings/databases/googlesettings.db $BACKUPDIR/other/googlesettings.db
	sudo adb pull /data/data/com.android.launcher/databases/launcher.db $BACKUPDIR/other/launcher.db
	sudo adb pull /data/data/com.android.providers.userdictionary/databases/user_dict.db $BACKUPDIR/other/user_dict.db
	echo "---------- Backed Other Settings"
	sudo chown -R $USER $BACKUPDIR
	zenity --notification --window-icon=/usr/local/abrtool/abrtool.ico --text "Successfully Backed-up Android device to $BACKUPDIR" --title "Android-Backup-Recovery"
	zenity --info --text "Successfully Backed-up Android device to $BACKUPDIR" --title "Android-Backup-Recovery"
}
restorescript() {
	export PATH=$PATH:$BACKUPDIR
	sudo echo "Gaining root privleges for adb..."
	sudo adb kill-server
	#sudo adb push $BACKUPDIR/apps /system/sd/app
	echo "----------- Installing Applications"
	cd $BACKUPDIR/apps
	for searchfile in ./*.apk
		do
		echo "------------ Processing $searchfile"
		sudo adb install "$searchfile" | zenity --progress --text "Installing $1" --pulsate
	done
	echo "---------- Restored Applications"
	sudo adb shell su
	sudo adb shell fix_permissions
	echo "---------- Fixed Application Permissions"
	sudo adb push $BACKUPDIR/msgs/mmssms.db /data/data/com.android.providers.telephony/databases/mmssms.db
	echo "---------- Restored Messages"
	sudo adb push $BACKUPDIR/bookmarks/browser.db /data/data/com.android.browser/databases/browser.db
	echo "---------- Restored Bookmarks"
	echo "---------- (Please, make sure to restart your browser)"
	sudo adb push $BACKUPDIR/other/alarms.db /data/data/com.android.alarmclock/databases/alarms.db 
	sudo adb push $BACKUPDIR/other/googlesettings.db /data/data/com.google.android.providers.settings/databases/googlesettings.db
	sudo adb push $BACKUPDIR/other/launcher.db adb pull /data/data/com.android.launcher/databases/launcher.db
	sudo adb push $BACKUPDIR/other/user_dict.db /data/data/com.android.providers.userdictionary/databases/user_dict.db
	echo "---------- Restored Other Settings"
	zenity --info --text "Successfully Restored Android device from $BACKUPDIR" --title "Android-Backup-Recovery"
	ans=$(zenity  --width=360 --height=220 --title="Power" --text="Would you like to reboot your device?" --list --radiolist --column "" --column "" Yes Reboot No Back-to-Shell); echo $ans
}

installabr()
{
	echo "---------- Removing previous installations"
	sudo rm -Rf /usr/local/abrtool
	sudo rm /usr/local/bin/abrtool
	echo "---------- Install Android-Backup-Recovery Tool"
	sudo mkdir /usr/local/abrtool
	sudo cp $PWD/*.* /usr/local/abrtoolv
	sudo cp $PWD/abrtool /usr/local/abrtool
	sudo ln -s /usr/local/abrtool/abrtool /usr/local/bin/abrtool
	zenity --info --text "Successfully Installed" --title "Android-Backup-Recovery"
}

print_usage()
{
	echo ""
	echo "Usage: $0 -b --backup"
	echo "       $0 -r --restore"
	echo "       $0 -i --install"
	echo "       $0 -v --version"
	echo ""
	echo "Valid arugments"
	echo "-b --backup, Backup device to computer"
	echo "-r --restore, Restore device from computer"
	echo ""
	echo "-i --install, Install abrtool"
	echo "-v --version, Version"
	echo ""
}
print_version()
{
	echo ""
	echo "Android-Backup-Restore Tools"
	echo "Version $VERSION"
	echo "Last Updated on $LASTUPDATED"
	echo ""
}
if [ $# -lt 1 ]
then
	print_usage
	exit 1
fi
while [ -n "$1" ]
do
	case "$1" in
	-b)
		backupscript
		shift
		;;
	--backup)
		backupscript
		shift
		;;
	-r)
		backupscript
		shift
		;;
	--restore)
		backupscript
		shift
		;;
	-i)
		installabr
		shift
		;;
	--install)
		installabr
		shift
		;;
	-v)
		print_version
		shift
		;;
	--version)
		print_version
		shift
		;;
	*)
		print_usage
		exit 1
	esac
done

# Reboot or Not
case $ans in
    Reboot)
        adb shell reboot
	zenity --info --text "Rebooting Device"
    ;;
    Back-to-Shell)
        exit
    ;;
esac
exit
